import type { Member, Class, Event, Ministry, MusicTeamMember } from "./types"

export const members: Member[] = [
  {
    id: "1",
    name: "John Dela Cruz",
    role: "Victory Group Leader",
    email: "john@victory.ph",
    phone: "+63 917 123 4567",
    address: "Quezon City, Metro Manila",
    ministry: "Worship Team",
    avatar: "/thoughtful-man.png",
    dateJoined: "2023-01-15",
    status: "active",
  },
  {
    id: "2",
    name: "Maria Santos",
    role: "Kids Church Leader",
    email: "maria@victory.ph",
    phone: "+63 917 234 5678",
    address: "Marikina City, Metro Manila",
    ministry: "Kids Ministry",
    dateJoined: "2023-03-20",
    status: "active",
  },
  {
    id: "3",
    name: "Peter Reyes",
    role: "Youth Leader",
    email: "peter@victory.ph",
    phone: "+63 917 345 6789",
    address: "Pasig City, Metro Manila",
    ministry: "Youth Ministry",
    dateJoined: "2023-02-10",
    status: "active",
  },
  {
    id: "4",
    name: "Sarah Lim",
    role: "Worship Leader",
    email: "sarah@victory.ph",
    phone: "+63 917 456 7890",
    address: "Makati City, Metro Manila",
    ministry: "Worship Team",
    dateJoined: "2023-04-05",
    status: "active",
  },
]

export const classes: Class[] = [
  {
    id: "1",
    name: "Victory Weekend",
    instructor: "Pastor Mike",
    schedule: "Sundays 10:00 AM",
    members: 150,
    description: "Main worship service",
    location: "Main Sanctuary",
  },
  {
    id: "2",
    name: "Victory Group",
    instructor: "John Dela Cruz",
    schedule: "Fridays 7:00 PM",
    members: 12,
    description: "Small group Bible study",
    location: "Room 201",
  },
  {
    id: "3",
    name: "Kids Church",
    instructor: "Maria Santos",
    schedule: "Sundays 10:00 AM",
    members: 25,
    description: "Children's ministry program",
    location: "Kids Room",
  },
  {
    id: "4",
    name: "Youth Service",
    instructor: "Peter Reyes",
    schedule: "Saturdays 6:00 PM",
    members: 35,
    description: "Youth worship and fellowship",
    location: "Youth Hall",
  },
]

export const events: Event[] = [
  {
    id: "1",
    title: "Victory Weekend Service",
    date: "2024-01-14",
    time: "10:00 AM",
    description: "Weekly worship service",
    type: "service",
    location: "Main Sanctuary",
    organizer: "Pastor Mike",
  },
  {
    id: "2",
    title: "Leadership Meeting",
    date: "2024-01-16",
    time: "7:00 PM",
    description: "Monthly leadership meeting",
    type: "meeting",
    location: "Conference Room",
    organizer: "Pastor Mike",
  },
  {
    id: "3",
    title: "Youth Night",
    date: "2024-01-19",
    time: "6:00 PM",
    description: "Special youth event",
    type: "event",
    location: "Youth Hall",
    organizer: "Peter Reyes",
  },
  {
    id: "4",
    title: "Baptism Service",
    date: "2024-01-21",
    time: "2:00 PM",
    description: "Water baptism ceremony",
    type: "service",
    location: "Main Sanctuary",
    organizer: "Pastor Mike",
  },
]

export const ministries: Ministry[] = [
  {
    id: "1",
    name: "Worship Team",
    leader: "Sarah Lim",
    members: 15,
    description: "Leading worship through music and song",
  },
  {
    id: "2",
    name: "Kids Ministry",
    leader: "Maria Santos",
    members: 8,
    description: "Teaching and caring for children",
  },
  {
    id: "3",
    name: "Youth Ministry",
    leader: "Peter Reyes",
    members: 12,
    description: "Discipling and mentoring young people",
  },
  {
    id: "4",
    name: "Victory Groups",
    leader: "John Dela Cruz",
    members: 25,
    description: "Small group ministry and discipleship",
  },
]

export const musicTeamMembers: MusicTeamMember[] = [
  {
    id: "1",
    name: "Sarah Lim",
    instrument: "Vocals",
    email: "sarah@victory.ph",
    phone: "+63 917 456 7890",
    experience: "5 years leading worship",
    availability: "Sundays and Wednesdays",
    status: "active",
  },
  {
    id: "2",
    name: "Mark Garcia",
    instrument: "Guitar",
    email: "mark@victory.ph",
    phone: "+63 917 567 8901",
    experience: "3 years playing guitar",
    availability: "Sundays",
    status: "active",
  },
  {
    id: "3",
    name: "Lisa Chen",
    instrument: "Piano",
    email: "lisa@victory.ph",
    phone: "+63 917 678 9012",
    experience: "7 years classical piano",
    availability: "Sundays and special events",
    status: "active",
  },
]
